### PR TITLE
fix 'only once send image' bug.

### PR DESCRIPTION
**Pull request by blackmenthor**
Added grantUriPermission for every intent start.

### CODE REVIEW

**Comment by maral** [comment]
Hi @blackmenthor, thanks for attempting at tackling the bug. I tried your fix and it unfortunately did not make any difference, first time it worked as previously, second time this:
```
E/DatabaseUtils(24832): Writing exception to parcel
E/DatabaseUtils(24832): java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://cz.codit.stromysvobody.adv_provider/cache_files/1537807647.png from pid=25128, uid=10052 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(24832): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
E/DatabaseUtils(24832): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
E/DatabaseUtils(24832): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:492)
E/DatabaseUtils(24832): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:420)
E/DatabaseUtils(24832): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
E/DatabaseUtils(24832): 	at android.os.Binder.execTransact(Binder.java:697)
E/BpSurfaceComposerClient(24832): Failed to transact (-1)
```

Android basically behaves as if your fix has not given me the permission on the second try anyway :disappointed:

**Comment by blackmenthor** [comment]
> Hi @blackmenthor, thanks for attempting at tackling the bug. I tried your fix and it unfortunately did not make any difference, first time it worked as previously, second time this:
> 
> ```
> E/DatabaseUtils(24832): Writing exception to parcel
> E/DatabaseUtils(24832): java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://cz.codit.stromysvobody.adv_provider/cache_files/1537807647.png from pid=25128, uid=10052 requires the provider be exported, or grantUriPermission()
> E/DatabaseUtils(24832): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
> E/DatabaseUtils(24832): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
> E/DatabaseUtils(24832): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:492)
> E/DatabaseUtils(24832): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:420)
> E/DatabaseUtils(24832): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
> E/DatabaseUtils(24832): 	at android.os.Binder.execTransact(Binder.java:697)
> E/BpSurfaceComposerClient(24832): Failed to transact (-1)
> ```
> Android basically behaves as if your fix has not given me the permission on the second try anyway 😞

Hi @maral 
i actually used my repo to share on my company's apps and it worked. Maybe when the user is prompted to allow the permission, the "No" btn is clicked. Or, it got something to do with your flutter project.

The syntax i used is 
AdvancedShare.generic(msg: message, url: base64ImageUrl).then((response) {
      handleResponse(response);
    });

**Comment by maral** [comment]
Thanks, I will try it when I get back to my project :+1: I was just using
`await AdvancedShare.generic(msg: message, url: base64ImageUrl)`

**Comment by maral** [comment]
Nope, same problems. Interesting to point out, it works fine in my emulator (API 26), but the bug happens on my phone (API 27). Who knows why...

**Pull request merged**
